"""initial

Revision ID: 502cd37b0210
Revises: 
Create Date: 2026-03-25 22:42:45.268784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '502cd37b0210'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calculated_stages', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('SAVED', 'NOT_CLOSED', 'CLOSED', name='stagestatus'),
               nullable=False,
               existing_server_default=sa.text("'saved'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calculated_stages', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('SAVED', 'NOT_CLOSED', 'CLOSED', name='stagestatus'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'saved'"))

    # ### end Alembic commands ###
